apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80  # Port exposed by the Service
      targetPort: 80  # Port to which traffic is forwarded inside the Pod
  type: ClusterIP  # Exposes the Service internally within the cluster
